npdat: 2 # 2 data files
npnet: 4 # 4 network partitions

filedir: "testnet"
filebase: "testnet"

rngseed:  2032
tmax:      100  # 100 milliseconds
tqueue:     20  # 20 milliseconds

runmode: "sim"
startpaused: yes
